server:
  port: 8888
  profiles:
    active: twitter_to_kafka

logging:
  level:
    root: info
    org.springframework.cloud.config: info

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oleksandrtest/config-server-repository
          default-label: main
          username: oleksandrtest
          password: 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
          clone-on-start: true
      fail-fast: true
